language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install .[test] pep8 coverage coveralls"

script:
  - nosetests nosetests --with-coverage --cover-package=prettyip
  - pep8 prettyip.py

after_success:
  - coveralls
